Alert title 0 num lines
urbn/URBNSwiftAlert pull request #16
Opened 2018-02-05 16:46 UTC by KVTaniguchi

The purpose of this PR is to remove the number of lines limit on alert titles since WL will have alert titles longer than 2 lines, especially in stores BOPIS.

2018-02-05 18:48 UTC, codecaffeine requested changes

2018-02-05 18:48 UTC, codecaffeine commented on URBNSwiftAlert/Classes/AlertView.swift
> -            titleLabel.lineBreakMode = .byWordWrapping
Why remove the `.likeBreakMode`?

2018-02-06 02:18 UTC, KVTaniguchi commented
@codecaffeine  updated

2018-02-06 14:05 UTC, ryang1428 approved these changes

2018-02-06 16:20 UTC, codecaffeine approved these changes

2018-02-06 16:20 UTC, merged